spring:
  application:
    name: producer
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    
producer:
  max-client-count: ${MAX_CLIENT_COUNT:10}
  max-message-count: ${MAX_MESSAGE_COUNT:10}
  delay-between-messages: ${DELAY_BETWEEN_MESSAGES:50}
